#!/bin/bash
.././calctitles.sh ../../bnw_224x224/00
.././calctitles.sh ../../bnw_224x224/01
.././calctitles.sh ../../bnw_224x224/02
.././calctitles.sh ../../bnw_224x224/03
.././calctitles.sh ../../bnw_224x224/04
.././calctitles.sh ../../bnw_224x224/05
.././calctitles.sh ../../bnw_224x224/06
.././calctitles.sh ../../bnw_224x224/07
.././calctitles.sh ../../bnw_224x224/08
.././calctitles.sh ../../bnw_224x224/09
