#!/bin/bash
.././calctitles.sh ../../bnw_224x224/20
.././calctitles.sh ../../bnw_224x224/21
.././calctitles.sh ../../bnw_224x224/22
.././calctitles.sh ../../bnw_224x224/23
.././calctitles.sh ../../bnw_224x224/24
.././calctitles.sh ../../bnw_224x224/25
.././calctitles.sh ../../bnw_224x224/26
.././calctitles.sh ../../bnw_224x224/27
.././calctitles.sh ../../bnw_224x224/28
.././calctitles.sh ../../bnw_224x224/29
