#!/bin/bash
.././calctitles.sh ../../bnw_224x224/30
.././calctitles.sh ../../bnw_224x224/31
.././calctitles.sh ../../bnw_224x224/32
.././calctitles.sh ../../bnw_224x224/33
.././calctitles.sh ../../bnw_224x224/34
.././calctitles.sh ../../bnw_224x224/35
.././calctitles.sh ../../bnw_224x224/36
.././calctitles.sh ../../bnw_224x224/37
.././calctitles.sh ../../bnw_224x224/38
.././calctitles.sh ../../bnw_224x224/39
