#!/bin/bash
.././calctitles.sh ../../bnw_224x224/40
.././calctitles.sh ../../bnw_224x224/41
.././calctitles.sh ../../bnw_224x224/42
.././calctitles.sh ../../bnw_224x224/43
.././calctitles.sh ../../bnw_224x224/44
.././calctitles.sh ../../bnw_224x224/45
.././calctitles.sh ../../bnw_224x224/46
.././calctitles.sh ../../bnw_224x224/47
.././calctitles.sh ../../bnw_224x224/48
.././calctitles.sh ../../bnw_224x224/49
